import { NoArgsFunction, NoArgsVoidFunction } from '@xaendar/types';
import { effect } from '../signals';

/**
 * Represents a single branch of a conditional structure (`if` / `else if` / `else`).
 *
 * @property condition - Function that evaluates the branch condition and returns a boolean.
 *   If absent, the branch is always considered valid (represents the `else` branch).
 * @property block - Function that, when executed, applies the branch's side effects and
 *   returns the list of cleanup (unwatch) functions generated within it.
 */
type Block = {
  condition?: NoArgsFunction<boolean>,
  block: NoArgsFunction<NoArgsVoidFunction[]>
};

/**
 * Creates a reactive conditional structure from a list of branches.
 *
 * Depending on the number of branches provided, the appropriate evaluation strategy
 * is selected:
 * - 1 branch  → simple `if` (see {@link handleIf});
 * - 2 branches → `if` / `else` (see {@link handleIfElse});
 * - 3+ branches → `if` / `else if` / ... / `else` (see {@link handleIfElseIf}).
 *
 * The evaluation is wrapped in an {@link effect}, so it is automatically re-executed
 * whenever any signal read by the conditions changes. On each re-execution, the current
 * state (which branch is active) and the related cleanup functions are only updated if
 * the active branch has actually changed.
 *
 * @param unwatchFns - Shared array that collects all active cleanup functions.
 *   Mutated in place: the created effect and branch functions are added to and
 *   removed from this array.
 * @param blocks - Ordered list of conditional branches to evaluate.
 */
export function _if(unwatchFns: NoArgsVoidFunction[], blocks: Block[]): void {
  let state: number | null = null;
  let localUnwatchFns = new Array<NoArgsVoidFunction>;
  let fn: () => { state: number | null, fns: NoArgsVoidFunction[] } | undefined;

  switch (blocks.length) {
    case 1:
      fn = () => handleIf(blocks[0]!, state, unwatchFns, localUnwatchFns);
      break;

    case 2:
      fn = () => handleIfElse(blocks[0]!, blocks[1]!, state, unwatchFns, localUnwatchFns);
      break;

    default:
      fn = () => handleIfElseIf(blocks, state, unwatchFns, localUnwatchFns);
  }

  const unlistener = effect(() => {
    const retVal = fn!();
    if (retVal) {
      state = retVal.state;
      localUnwatchFns = retVal.fns;
    }
  });

  unwatchFns.push(unlistener);
}

/**
 * Handles the simple `if` case (a single branch, no `else`).
 *
 * If the condition is true, the branch is activated (state `0`); otherwise, any
 * previously active branch is deactivated by resetting the state to `null` and
 * executing an empty block.
 *
 * @param ifBlock - The `if` branch to evaluate.
 * @param state - The current state (index of the active branch, or `null` if none).
 * @param unwatchFns - Shared array of active cleanup functions.
 * @param localUnwatchFns - Cleanup functions generated by the last branch activation.
 * @returns The new state and new cleanup functions if the active branch changed,
 *   otherwise `undefined`.
 */
function handleIf(
  ifBlock: Block,
  state: number | null,
  unwatchFns: NoArgsVoidFunction[],
  localUnwatchFns: NoArgsVoidFunction[]
): { state: number | null, fns: NoArgsVoidFunction[] } | undefined {
  return ifBlock.condition!() 
    ? checkAndUpdateState(state, 0, ifBlock.block, unwatchFns, localUnwatchFns) 
    : checkAndUpdateState(state, null, () => [], unwatchFns, localUnwatchFns);
}

/**
 * Handles the `if` / `else` case (exactly two branches).
 *
 * If the `if` condition is true, the first branch is activated (state `0`); otherwise,
 * the `else` branch is activated (state `1`).
 *
 * @param ifBlock - The `if` branch to evaluate.
 * @param elseBlock - The `else` branch used when the `if` condition is false.
 * @param state - The current state (index of the active branch, or `null` if none).
 * @param unwatchFns - Shared array of active cleanup functions.
 * @param localUnwatchFns - Cleanup functions generated by the last branch activation.
 * @returns The new state and new cleanup functions if the active branch changed,
 *   otherwise `undefined`.
 */
function handleIfElse(
  ifBlock: Block,
  elseBlock: Block,
  state: number | null,
  unwatchFns: NoArgsVoidFunction[],
  localUnwatchFns: NoArgsVoidFunction[]
): { state: number | null, fns: NoArgsVoidFunction[] } | undefined {
  return ifBlock.condition!()
    ? checkAndUpdateState(state, 0, ifBlock.block, unwatchFns, localUnwatchFns)
    : checkAndUpdateState(state, 1, elseBlock.block, unwatchFns, localUnwatchFns);
}

/**
 * Handles the general case of an `if` / `else if` / ... / `else` chain (three or more branches).
 *
 * Iterates through the branches in order and activates the first one whose condition is
 * true; a branch without a condition is always considered valid and acts as the final
 * `else`. The state is set to the index of the activated branch.
 *
 * @param blocks - Ordered list of conditional branches to evaluate.
 * @param state - The current state (index of the active branch, or `null` if none).
 * @param unwatchFns - Shared array of active cleanup functions.
 * @param localUnwatchFns - Cleanup functions generated by the last branch activation.
 * @returns The new state and new cleanup functions if the active branch changed,
 *   otherwise `undefined`. Also returns `undefined` if no branch matches.
 */
function handleIfElseIf(
  blocks: Block[],
  state: number | null,
  unwatchFns: NoArgsVoidFunction[],
  localUnwatchFns: NoArgsVoidFunction[]
): { state: number | null, fns: NoArgsVoidFunction[] } | undefined {
  for (let i = 0; i < blocks.length; i++) {
    const { condition, block } = blocks[i]!;
    if (!condition || condition()) {
      return checkAndUpdateState(state, i, block, unwatchFns, localUnwatchFns);
    }
  }
}

/**
 * Updates the conditional structure state only when the active branch changes.
 *
 * If `newState` differs from `state`:
 * 1. runs cleanup of the previous branch's functions (see {@link unwatch});
 * 2. executes the new branch's block via {@link Signal.subtle.untrack} to avoid
 *    creating unwanted reactive dependencies during block execution;
 * 3. registers the new cleanup functions in the shared `unwatchFns` array.
 *
 * If the branch has not changed, no operation is performed.
 *
 * @param state - The current state (index of the active branch, or `null` if none).
 * @param newState - The new state to set (index of the branch to activate, or `null`).
 * @param conditionalBlockFn - Branch function to execute, which returns its own
 *   cleanup functions.
 * @param unwatchFns - Shared array of active cleanup functions.
 * @param localUnwatchFns - Cleanup functions of the currently active branch, to be
 *   removed before activating the new branch.
 * @returns Il nuovo stato e le nuove funzioni di cleanup se il ramo è cambiato, altrimenti
 *   `undefined`.
 */
function checkAndUpdateState(
  state: number | null,
  newState: number | null,
  conditionalBlockFn: NoArgsFunction<NoArgsVoidFunction[]>,
  unwatchFns: NoArgsVoidFunction[],
  localUnwatchFns: NoArgsVoidFunction[]
): { state: number | null, fns: NoArgsVoidFunction[] } | undefined {
  if (state !== newState) {
    unwatch(unwatchFns, localUnwatchFns);
    localUnwatchFns = Signal.subtle.untrack<NoArgsVoidFunction[]>(conditionalBlockFn);
    unwatchFns.push(...localUnwatchFns);
    return { state: newState, fns: localUnwatchFns };
  }
}

/**
 * Executes and removes the cleanup functions of the previously active branch.
 *
 * For each local function: removes it from the shared `unwatchFns` array (if present)
 * and then invokes it to release resources / tear down associated subscriptions.
 *
 * @param unwatchFns - Shared array of active cleanup functions, mutated in place.
 * @param localUnwatchFns - Cleanup functions of the branch to deactivate.
 */
export function unwatch(unwatchFns: NoArgsVoidFunction[], localUnwatchFns: NoArgsVoidFunction[]) {
  for (const fn of localUnwatchFns) {
    const index = unwatchFns.indexOf(fn);
    if (index !== -1) {
      unwatchFns.splice(index, 1);
    }
    fn();
  }
}